#!/usr/bin/env python3
"""
Flight Alert App - API Setup Helper
This script helps you configure API keys for real notifications
"""

import os
import sys

def create_env_file():
    """Create .env file with user input"""
    print("🔧 Flight Alert App - API Setup")
    print("=" * 50)
    print()
    
    # Check if .env already exists
    if os.path.exists('.env'):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/n): ")
        if overwrite.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print("Let's set up your API keys for real notifications!")
    print()
    
    # Email configuration
    print("📧 EMAIL NOTIFICATIONS (SendGrid)")
    print("-" * 30)
    print("1. Go to: https://sendgrid.com/")
    print("2. Sign up for free account")
    print("3. Create API key in Settings → API Keys")
    print("4. Verify sender email in Settings → Sender Authentication")
    print()
    
    sendgrid_key = input("Enter your SendGrid API key (or press Enter to skip): ").strip()
    from_email = input("Enter your verified sender email (or press Enter to skip): ").strip()
    
    print()
    
    # SMS configuration
    print("📱 SMS NOTIFICATIONS (Twilio)")
    print("-" * 30)
    print("1. Go to: https://console.twilio.com/")
    print("2. Sign up for free account")
    print("3. Get Account SID and Auth Token from dashboard")
    print("4. Buy a phone number in Phone Numbers → Manage")
    print()
    
    twilio_sid = input("Enter your Twilio Account SID (or press Enter to skip): ").strip()
    twilio_token = input("Enter your Twilio Auth Token (or press Enter to skip): ").strip()
    twilio_phone = input("Enter your Twilio phone number (+1234567890): ").strip()
    
    print()
    
    # Create .env file
    env_content = f"""# Flight Alert App Configuration
# Generated by setup script

# Email Configuration (SendGrid)
SENDGRID_API_KEY={sendgrid_key}
FROM_EMAIL={from_email}

# SMS Configuration (Twilio)
TWILIO_ACCOUNT_SID={twilio_sid}
TWILIO_AUTH_TOKEN={twilio_token}
TWILIO_PHONE_NUMBER={twilio_phone}

# Flight API Configuration (Optional - for real flight data)
AMADEUS_API_KEY=
AMADEUS_API_SECRET=

# App Configuration
DATABASE_URL=sqlite:///flight_alerts.db
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("✅ .env file created successfully!")
        print()
        
        # Check what was configured
        configured = []
        if sendgrid_key and from_email:
            configured.append("📧 Email notifications")
        if twilio_sid and twilio_token and twilio_phone:
            configured.append("📱 SMS notifications")
        
        if configured:
            print("🎉 Configured services:")
            for service in configured:
                print(f"   {service}")
            print()
            print("🔄 Restart the app to activate real notifications:")
            print("   python start_app.py")
        else:
            print("⚠️  No services configured - app will run in demo mode")
            print("   You can run this setup script again anytime")
        
    except Exception as e:
        print(f"❌ Error creating .env file: {e}")

def test_configuration():
    """Test the current configuration"""
    print("🧪 Testing Current Configuration")
    print("=" * 50)
    
    try:
        from config import Config
        config = Config()
        
        print("Email Configuration:")
        print(f"  SendGrid API Key: {'✅ Configured' if config.SENDGRID_API_KEY else '❌ Not configured'}")
        print(f"  From Email: {'✅ Configured' if config.FROM_EMAIL else '❌ Not configured'}")
        print()
        
        print("SMS Configuration:")
        print(f"  Twilio Account SID: {'✅ Configured' if config.TWILIO_ACCOUNT_SID else '❌ Not configured'}")
        print(f"  Twilio Auth Token: {'✅ Configured' if config.TWILIO_AUTH_TOKEN else '❌ Not configured'}")
        print(f"  Twilio Phone: {'✅ Configured' if config.TWILIO_PHONE_NUMBER else '❌ Not configured'}")
        print()
        
        if config.SENDGRID_API_KEY and config.FROM_EMAIL:
            print("📧 Email notifications: READY")
        else:
            print("📧 Email notifications: DEMO MODE")
        
        if config.TWILIO_ACCOUNT_SID and config.TWILIO_AUTH_TOKEN and config.TWILIO_PHONE_NUMBER:
            print("📱 SMS notifications: READY")
        else:
            print("📱 SMS notifications: DEMO MODE")
            
    except Exception as e:
        print(f"❌ Error testing configuration: {e}")

def main():
    """Main setup function"""
    if len(sys.argv) > 1 and sys.argv[1] == 'test':
        test_configuration()
    else:
        create_env_file()

if __name__ == "__main__":
    main()
